DROP TABLE IF EXISTS ADDRESSES;
CREATE TABLE ADDRESSES (ID INT AUTO_INCREMENT PRIMARY KEY,
STREET VARCHAR(100) NOT NULL,
STREET_NUMBER INT NOT NULL,
LOCATION VARCHAR(100) NOT NULL,
PROVINCE VARCHAR(100) NOT NULL);

DROP TABLE IF EXISTS PATIENT;
CREATE TABLE PATIENT (ID INT AUTO_INCREMENT PRiMARY KEY,
NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
CARD_IDENTITY INT NOT NULL,
ADMISSION_OF_DATE DATE NOT NULL,
ADDRESS_ID VARCHAR(100) NOT NULL);

DROP TABLE IF EXISTS DENTIST;
CREATE TABLE DENTIST (
ID INT AUTO_INCREMENT PRIMARY KEY,
REGISTRATION INT NOT NULL,
NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL);

INSERT INTO ADDRESSES (STREET, STREET_NUMBER, LOCATION, PROVINCE)
VALUES('Laprida',1175,'Sáenz Peña', 'Chaco');

INSERT INTO PATIENT(NAME, LAST_NAME, EMAIL, CARD_IDENTITY,ADMISSION_OF_DATE,ADDRESS_ID)
VALUES('Martin','Piccato','prueba@gmail.com',26673164,'2025-01-01', 1);
INSERT INTO DENTIST (REGISTRATION, NAME, LAST_NAME)
VALUES(1,'Martin', 'Piccato');
INSERT INTO DENTIST (REGISTRATION, NAME,LAST_NAME)
VALUES (2,"LORENZO","PICCATO")